### ISSUE TITLE
if support for bedrock player?

### ISSUE THREAD

**Issue by TimmyYue** [ADHDMC/InvisibleFrames#2]
on title

**Comment by Peashooter101** [comment]
Unfortunately, we will not provide official support to Bedrock Players (I assume using Geyser).

However, due to the simplistic nature of the plugin, I feel like you already can do this on Bedrock.

The plugin checks for three things:

- Right-Click (Use Item) Interaction with Item Frame
- If the player is crouching / sneaking during the interaction.
- If the player has permission `invisibleframes.toggleframes`.
